// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

// Result for joining or creating a game. Contains an authentication token and the game.
type JoinGameResult struct {
	// A token used to authenticate using the Authorization header.
	Token string `json:"token"`
	// The game joined/created.
	Game *Game `json:"game"`
}

// A player can either be the X or the O.
type PlayerType string

const (
	PlayerTypeX PlayerType = "X"
	PlayerTypeO PlayerType = "O"
)

var AllPlayerType = []PlayerType{
	PlayerTypeX,
	PlayerTypeO,
}

func (e PlayerType) IsValid() bool {
	switch e {
	case PlayerTypeX, PlayerTypeO:
		return true
	}
	return false
}

func (e PlayerType) String() string {
	return string(e)
}

func (e *PlayerType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlayerType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlayerType", str)
	}
	return nil
}

func (e PlayerType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
